services:
  masteringx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - masteringx-storage-production:/var/www/storage:ro
      - public:/var/www/public/build:ro
    networks:
      - masteringx-production
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: .
      dockerfile: docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - public:/var/www/public/build
      - masteringx-storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - masteringx-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-app}
      - POSTGRES_USER=${POSTGRES_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - masteringx-production
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  redis:
#    image: redis:alpine
#    restart: unless-stopped  # Automatically restart unless the service is explicitly stopped
#    networks:
#      - masteringx-production
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 3

networks:
  masteringx-production:

volumes:
  postgres-data-production:
  masteringx-storage-production:
  public:
